projects:
  PortfolioArticles:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: m6uzkpwnxzebbla7ou4p66nkxa
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://wqerrsgtnvcfrkmhxvo5qmqoua.appsync-api.us-east-1.amazonaws.com/graphql
